---
- name: Creating agents 
  block:
    - name: Getting script for booting
      template:
        src: ../templates/boot_nodes.py
        dest: /root/ansible_workdir/boot_nodes.py

    - name: Debug 
      debug: 
        msg: "Booting {{ env.cluster.networking.metadata_name }}-{{ item }}"

    - name: Print multiple line debug message
      debug:
        msg: "{{ multiline_message | join('\n') }}"
      vars:
        multiline_message:
          - --zvmname "{{ zvm.nodes[item].name }}"
          - --zvmhost "{{ zvm.nodes[item].host }}"
          - --zvmuser "{{ zvm.nodes[item].user }}"
          - --zvmpass "{{ zvm.nodes[item].password }}"
          - --cpu "{{ zvm.vcpus }}"
          - --memory "{{ zvm.memory }}"
          - --network "{{ zvm.network_mode }}"

    - name: Booting zvm node
      shell: |
        python /root/ansible_workdir/boot_nodes.py \
        --zvmname "{{ zvm.nodes[item].name }}" \
        --zvmhost "{{ zvm.nodes[item].host }}" \
        --zvmuser "{{ zvm.nodes[item].user }}" \
        --zvmpass "{{ zvm.nodes[item].password }}" \
        --cpu "{{ zvm.vcpus }}" \
        --memory "{{ zvm.memory }}" \
        --kernel 'file:///var/lib/libvirt/images/pxeboot/kernel.img'  \
        --initrd 'file:///var/lib/libvirt/images/pxeboot/initrd.img' \
        --cmdline "$(cat /root/ansible_workdir/{{ env.cluster.networking.metadata_name }}-{{ item }}.param)" \
        --network "{{ zvm.network_mode }}"

    - name:  Attaching dasd disk
      shell: vmcp attach {{ zvm.nodes[item].dasd.disk_id }} to {{ zvm.nodes[item].name }} 
      when: zvm.disk_type | lower == 'dasd'
    
    - name: Attaching fcp disks
      shell: vmcp attach {{ zvm.nodes[item].lun[0].paths[0].fcp.split('.')[-1] }} to {{ zvm.nodes[item].name }}
      when: zvm.disk_type | lower == 'fcp'
