---
- name: Create qemu image for agents
  command: "qemu-img create -f qcow2 {{ hypershift.agents_parms.storage.pool_path }}{{ hypershift.hcp.hosted_cluster_name }}-agent{{ item }}.qcow2 {{ hypershift.agents_parms.disk_size }}"
  loop: "{{ range(hypershift.agents_parms.agents_count|int) | list }}"

- name: Boot Agents
  shell: |
    {% if hypershift.agents_parms.static_ip_parms.static_ip == true %}
    mac_address=$(oc get NmStateConfig static-ip-nmstate-config-{{ hypershift.hcp.hosted_cluster_name }}-{{ item }} -n {{ hypershift.hcp.clusters_namespace }}-{{ hypershift.hcp.hosted_cluster_name }} -o json | jq -r '.spec.interfaces[] | .macAddress')
    {% else %}
    mac_address="{{ hypershift.agents_parms.agent_mac_addr[item] }}"
    {% endif %}

    virt-install \
    --name "{{ hypershift.hcp.hosted_cluster_name }}-agent-{{ item }}" \
    --osinfo detect=on,require=off \
    --autostart \
    --ram="{{ hypershift.agents_parms.ram }}" \
    --cpu host \
    --vcpus="{{ hypershift.agents_parms.vcpus }}"  \
    --location "/var/lib/libvirt/images/pxeboot/,kernel=kernel.img,initrd=initrd.img" \
    --disk {{ hypershift.agents_parms.storage.pool_path }}{{ hypershift.hcp.hosted_cluster_name }}-agent{{ item }}.qcow2 \
    --network network:{{ env.vnet_name }},mac=$mac_address \
    --graphics none \
    --noautoconsole  \
    --wait=-1 \
    --extra-args "rd.neednet=1 nameserver={{ hypershift.agents_parms.nameserver }}" \
    --extra-args "coreos.live.rootfs_url=http://{{ hypershift.bastion_hypershift }}:8080/rootfs.img random.trust_cpu=on rd.luks.options=discard ignition.firstboot ignition.platform.id=metal" \
    --extra-args "console=tty1 console=ttyS1,115200n8 coreos.inst.persistent-kargs=console=tty1 console=ttyS1,115200n8"
  async: 3600
  poll: 0
  loop: "{{ range(hypershift.agents_parms.agents_count|int) | list }}"

