---

- name: Load in variables
  tags: ssh_copy_id, ssh
  include_vars: "{{inventory_dir}}/group_vars/all.yaml"

- name: Get ansible.pub key for check in next task
  tags: ssh_copy_id, ssh
  set_fact:
    ans_pub_key: "{{ lookup('file', '~/.ssh/{{ env.ansible_key_name }}.pub') }}"

- name: Print Ansible public key
  tags: ssh_copy_id, ssh
  debug:
    msg: "{{ ans_pub_key }}"

- name: Delete SSH key from known hosts if it already exists for idempotency
  tags: ssh_copy_id, ssh
  lineinfile:
    path: "~/.ssh/known_hosts"
    line: "{{ ssh_target[0] }}"
    state: absent

- name: Use template file to create expect script
  tags: ssh_copy_id, ssh
  template:
    src: ssh-copy-id.exp.j2
    dest: "{{ role_path }}/files/ssh-copy-id-expect-pass.exp"
    force: yes

- name: Copy SSH ID to remote host with pre-provided password
  tags: ssh_copy_id, ssh
  command: "expect {{ role_path }}/files/ssh-copy-id-expect-pass.exp"
  register: ssh_copy

- name: Print results of copying ssh id to remote host.
  tags: ssh_copy_id, ssh
  debug:
    var: ssh_copy

- name: Delete templated expect script
  tags: ssh_copy_id, ssh
  file:
    path: "{{ role_path }}/files/ssh-copy-id-expect-pass.exp"
    state: absent

- name: Re-create ssh-copy-id files folder
  tags: ssh_copy_id, ssh
  file:
    path: "{{ role_path }}/files/"
    state: directory