---
- name: Install Packages on zvm host
  yum:
    name:
      - "{{ item }}"
    state: present
  loop: "{{ env.pkgs.zvm }}"

- name: Install setuptools_rust using pip
  pip:
    name: setuptools_rust
    executable: pip3

- name: Install cryptography using pip
  pip:
    name: cryptography
    executable: pip3

- name: Clone tessia-baselib repository
  git:
    repo: https://gitlab.com/tessia-project/tessia-baselib.git
    dest: /root/ansible_workdir/tessia-baselib

- name: Change directory to tessia-baselib and install dependencies using pip3
  shell: cd /root/ansible_workdir/tessia-baselib ; pip3 install -U .

