---

- name: Template and update RHEL configuration files for KVM host to boot from
  hosts: file_server
  tags: update_cfgs, update, kvm_host_1
  become: false
  gather_facts: false
  tasks:
    - name: Include vars for the KVM host.
      ansible.builtin.include_vars:
        file: "{{ inventory_dir }}/host_vars/{{ env.z.lpar1.hostname }}.yaml"
      when: env.z.lpar1.create

    - name: Update configuration files for the KVM host.
      ansible.builtin.import_role:
        name: update_cfgs
      when: env.z.lpar1.create

- name: Template and update RHEL configuration files for KVM host to boot from
  hosts: file_server
  tags: update_cfgs, update, kvm_host_2
  become: false
  gather_facts: false
  vars_files:
    - "{{ inventory_dir }}/group_vars/all.yaml"
    - "{{ inventory_dir }}/group_vars/secrets.yaml"
  tasks:
    - name: Include vars for a second KVM host if it is to be created.
      ansible.builtin.include_vars:
        file: "{{ inventory_dir }}/host_vars/{{ env.z.lpar2.hostname }}.yaml"
      when: env.z.lpar2.create

    - name: Update configuration files for a second KVM host, if cluster is to be highly available
      ansible.builtin.import_role:
        name: update_cfgs
      when: env.z.lpar2.create

- name: Template and update RHEL configuration files for KVM host to boot from
  hosts: file_server
  tags: update_cfgs, update, kvm_host_3
  become: false
  gather_facts: false
  vars_files:
    - "{{ inventory_dir }}/group_vars/all.yaml"
    - "{{ inventory_dir }}/group_vars/secrets.yaml"
  tasks:
    - name: Include vars for third KVM host if it is to be created.
      ansible.builtin.include_vars:
        file: "{{ inventory_dir }}/host_vars/{{ env.z.lpar3.hostname }}.yaml"
      when: env.z.lpar3.create

    - name: Update configuration files for a third KVM host, if cluster is to be highly available
      ansible.builtin.import_role:
        name: update_cfgs
      when: env.z.lpar3.create

- name: Boot RHEL on LPAR 1
  hosts: localhost
  tags: create_kvm_host, boot, kvm_host_1
  connection: local
  tasks:
    - name: Include vars for first LPAR if it is to be created.
      ansible.builtin.include_vars:
        file: "{{ inventory_dir }}/host_vars/{{ env.z.lpar1.hostname }}.yaml"
      when: env.z.lpar1.create

    - name: Boot and install RHEL for KVM host
      ansible.builtin.import_role:
        name: create_kvm_host
      when: env.z.lpar1.create

- name: Boot RHEL on LPAR 2
  hosts: localhost
  tags: create_kvm_host, boot, kvm_host_2
  connection: local
  tasks:
    - name: Include vars for second KVM host.
      ansible.builtin.include_vars:
        file: "{{ inventory_dir }}/host_vars/{{ env.z.lpar2.hostname }}.yaml"
      when: env.z.lpar2.create

    - name: Boot and install RHEL for a second KVM host.
      ansible.builtin.import_role:
        name: create_kvm_host
      when: env.z.lpar2.create

- name: Boot RHEL on LPAR 3
  hosts: localhost
  tags: create_kvm_host, boot, kvm_host_3
  connection: local
  tasks:
    - name: Include vars for third KVM host.
      ansible.builtin.include_vars:
        file: "{{ inventory_dir }}/host_vars/{{ env.z.lpar3.hostname }}.yaml"
      when: env.z.lpar3.create

    - name: Boot and install RHEL for a third KVM host.
      ansible.builtin.import_role:
        name: create_kvm_host
      when: env.z.lpar3.create
